version: "3.7"

services:
  rbn-node-0:
    # platform: linux/arm64/v8
    image: ghcr.io/redbellynetwork/sevm-docker-full:20250227-001456
    container_name: rbn-node-0
    ports:
      - 8545:8545
    environment:
      - HTTP_PORT=8545
      - NODE_ID=0
      - CONSENSUS=dbft
      - SIGNING_KEY=211584689e71d1a45a7de6404f90402dc58b6867e6941f6026870727c73f2ffb
      - AUTH_PORT=10240
  rbn-node-1:
    # platform: linux/arm64/v8
    image: ghcr.io/redbellynetwork/sevm-docker-full:20250227-001456
    container_name: rbn-node-1
    depends_on:
      - rbn-node-0
    ports:
      - 8547:8547
    environment:
      - HTTP_PORT=8547
      - NODE_ID=1
      - CONSENSUS=dbft
      - SIGNING_KEY=6b1eb2d75ab719b147d6a3d9ab3828da63b8693b22190baf79eac9ccdb36a492
      - AUTH_PORT=10240
  rbn-node-2:
    # platform: linux/arm64/v8
    image: ghcr.io/redbellynetwork/sevm-docker-full:20250227-001456
    container_name: rbn-node-2
    depends_on:
      - rbn-node-1
    ports:
      - 8549:8549
    environment:
      - HTTP_PORT=8549
      - NODE_ID=2
      - CONSENSUS=dbft
      - SIGNING_KEY=a89260d1beca7d94b7ff14569a097539b152d8c99f3baf6eebbb9bf8fb543838
      - AUTH_PORT=10240
  rbn-node-3:
    # platform: linux/arm64/v8
    depends_on:
      - rbn-node-2
    image: ghcr.io/redbellynetwork/sevm-docker-full:20250227-001456
    container_name: rbn-node-3
    ports:
      - 8551:8551
    environment:
      - HTTP_PORT=8551
      - NODE_ID=3
      - CONSENSUS=dbft
      - SIGNING_KEY=d0a65cc3b4849960fd79f40d298011bbff180382666ce141c11d04238c6b46f7
      - AUTH_PORT=10240
