#!/bin/sh

current_branch=`git rev-parse --abbrev-ref HEAD`
if [[ $current_branch =~ master|main|dev ]]; then
    message="Please don't commit directly to $current_branch."
    echo -e "\033[1;31mERROR: $message\033[0m";
    exit 1
fi
branch_name=$(git branch | grep '*' | sed 's/* //')
ticket_name=${branch_name#*/}
ticket_id=${ticket_name%/*}

valid_branch_regex="^(feature|fix|hotfix)\/${ticket_id}+\/.*$|^Release\/.*$"

message="There is something wrong with your branch name. You should rename your branch to a valid name and try again."

if [[ ! $branch_name =~ $valid_branch_regex ]]
then
    echo "$message"
    exit 1
fi

PRIVATE_EMAIL_PATTERN=".*@users\\.noreply\\.github\\.com"

AUTHOR_EMAIL=$(git config user.email)
if ! echo "$AUTHOR_EMAIL" | grep -Eq "$PRIVATE_EMAIL_PATTERN"; then
    echo "Error: Commits must use a private email address (username@users.noreply.github.com)."
    echo "Current email: $AUTHOR_EMAIL"
    exit 1
fi

exit 0
