name: Release package
on:
  workflow_dispatch:
    inputs:
      versionTag:
        description: "Version tag to create tag and release"
        type: string
        required: true

jobs:
  release-package:
    runs-on: ubuntu-latest
    env:
      GIT_TOKEN: ${{ secrets.GIT_ACTIONS_TOKEN }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
        shell: bash
      - name: Generate artifacts
        run: npm run compile
        shell: bash
      - name: Prepare release
        id: release
        run: |
          echo "::set-output name=DATE::$(date +'%Y-%m-%d')"
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ github.event.inputs.versionTag }}
          name: Release v${{ github.event.inputs.versionTag }} ${{steps.release.outputs.DATE}}
          generateReleaseNotes: true
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_ACTIONS_TOKEN }}
