name: static-check

on:
  workflow_call:
jobs:
  static-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GIT_ACTIONS_TOKEN }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
        shell: bash
      - name: Generate artifacts
        run: npm run compile
        shell: bash
      - name: Solidity lint check
        run: npm run lint-check:solidity
        shell: bash
      - name: Solidity format check
        run: npm run format-check:solidity
        shell: bash
